### ISSUE TITLE
It does not works with vue3-typescript raise error Could not find a declaration file for module 'vue3-tabs'

### ISSUE THREAD

**Issue by tonytony2020** [HJ29/vue3-tabs#5]
my package.json

```
//...
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
//...
```

**Comment by HJ29** [comment]
can u share code about how u import and use the package?

**Comment by tonytony2020** [comment]
```
<script lang="ts">
import { Options, Vue } from 'vue-class-component';
import { Tabs, Tab } from 'vue3-tabs-component';

// ...

```


I walking around this issue by 
```
// @ts-ignore
import { Tabs, Tab } from 'vue3-tabs-component';
```

**Comment by HJ29** [comment]
> my package.json
> 
> ```
> //...
>   "dependencies": {
>     "core-js": "^3.6.5",
>     "vue": "^3.0.0",
>     "vue-class-component": "^8.0.0-0",
>     "vue-router": "^4.0.0-0",
>     "vuex": "^4.0.0-0"
>   },
> //...
> ```

did u `npm i --save vue3-tabs` or `yarn add vue3-tabs`
`vue3-tabs` package doesn't appear in your package.json


> ```
> <script lang="ts">
> import { Options, Vue } from 'vue-class-component';
> import { Tabs, Tab } from 'vue3-tabs-component';
> 
> // ...
> ```
> 
> I walking around this issue by
> 
> ```
> // @ts-ignore
> import { Tabs, Tab } from 'vue3-tabs-component';
> ```
you should import `vue3-tabs` instead of `vue3-tabs-component`.
u said that u workaround the issue by using ts-ignore, 
does that means u successfully used this package? or u didn't?

---
not sure if these are typo when u commenting here.
